#!/bin/bash -e

export PATH=/var/vcap/packages/ruby/bin:$PATH
RUN_DIR=/var/vcap/sys/run/vcap_registrar
LOG_DIR=/var/vcap/sys/log/vcap_registrar
PIDFILE=$RUN_DIR/login_vcap_registrar.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "VCAP registrar for Login Server"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    export CONFIG_FILE=/var/vcap/jobs/login/config/vcap_registrar/config.yml

    cd /var/vcap/packages/login/vcap_registrar
    exec /var/vcap/packages/ruby/bin/ruby \
         /var/vcap/packages/login/vcap_registrar/bin/vcap_registrar \
         --register_with_router \
         --register_varz_credentials \
         >>$LOG_DIR/login_vcap_registrar.stdout.log \
         2>>$LOG_DIR/login_vcap_registrar.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: login_vcap_registrar_ctl {start|stop}" ;;

esac
exit 0
